#!/bin/sh
set -e
package_name=plasma-desktop-icon-background
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/FolderItemDelegate.qml"
;;
esac
exit 0
